// Class automatically generated by Dev-C++ New Class wizard

#ifndef VIEWPORT_H
#define VIEWPORT_H

#include "base/object.h" // inheriting class's header file

using namespace base;

namespace engine3d {
/*
 * No description
 */
class Viewport : public Object
{
	public:
		// class constructor
		Viewport();
		Viewport(const Viewport& v);
		// class destructor
		~Viewport();
		int GetX() const;
		int GetY() const;
		int GetWidth() const;
		int GetHeight() const;
		int GetXC() const;
		int GetYC() const;
	protected:
        int x;
        int y;
        int width;
        int height;
        int xCenter;
        int yCenter;
};
}
#endif // VIEWPORT_H
