// Class automatically generated by Dev-C++ New Class wizard

#include "beziercurve.h" // class's header file
#include <math.h>

using namespace engine3d;

// class constructor
BezierCurve::BezierCurve(unsigned int order) :
    mOrder(order)
{

}

// class destructor
BezierCurve::~BezierCurve()
{
	// insert your code here
}

Vector BezierCurve::GetPoint(double parameter) const
{
    assert(parameter >= GetParameterMin() && parameter < GetParameterMax());
    int startingPoint = 0;
//    parameter *= mPoints.Size() / (mOrder + 1);
//    while (parameter >= 1) {
//        parameter -= 1;
//        startingPoint += mOrder;
//    }
    
    
    int k, kn, nn, nkn;
    double blend, muk, munk;
    Vector point(0.0, 0.0, 0.0);
    
    muk = 1;
    munk = pow(1 - parameter, (double) mPoints.Size() - 1);
    
    for (k = startingPoint; k < startingPoint + mPoints.Size(); k++) {
        nn = mPoints.Size() - 1;
        kn = k;
        nkn = mPoints.Size() - 1 - k;
        blend = muk * munk;
        muk *= parameter;
        munk /= (1 - parameter);
        while (nn >= 1) {
            blend *= nn;
            nn--;
            if (kn > 1) {
                blend /= (double) kn;
                kn--;
            }
            if (nkn > 1) {
                blend /= (double) nkn;
                nkn--;
            }
        }
        point += mPoints[k] * blend;
    }

    return point;
}
