// Class automatically generated by Dev-C++ New Class wizard

#include "parametriccurve.h" // class's header file

using namespace engine3d;

// class constructor
ParametricCurve::ParametricCurve()
{
	// insert your code here
}

// class destructor
ParametricCurve::~ParametricCurve()
{
	// insert your code here
}

void ParametricCurve::SetPoints(const ArrayList<Vector>& rPoints) {
    for (int i = 0; i < rPoints.Size(); i++) {
        mPoints.Add(rPoints[i]);
    }
}
