// Class automatically generated by Dev-C++ New Class wizard

#ifndef GEOMETRY_PROJECTOR_H
#define GEOMETRY_PROJECTOR_H

#include "base/list.h"
#include "base/object.h" // inheriting class's header file
#include "plane.h"

using namespace base;

namespace engine3d {
/*
 * Implements the parallel projection of a shape to a given plane
 */
class Projector : public Object
{
	public:
		// class constructor
	Projector();
		// class destructor
		~Projector();
		/**
		 * Adds the new projection plane.
		 * point - the coordinates of an arbitrary point in plane
		 * normal - normal vector of the plane
		 */
		void AddPlane(const Vector& point, const Vector& normal);
		void AddPlane(const Plane& plane);
		/**
		 * Sets the projection direction. The direction vector must 
		 * point towards the projection planes.
		 */
		void SetDirection(const Vector& direction);
		// No description
		Vector Project(const Vector& v) const;
	protected:
        ArrayList<Plane*> planes;
        Vector* d;
};
}
#endif // GEOMETRY_PROJECTOR_H
