// Class automatically generated by Dev-C++ New Class wizard

#include "projection.h" // class's header file
using namespace engine3d;
// class constructor
Projection::Projection() :
    d(0),
    planes(1)
{
}

// class destructor
Projection::~Projection()
{
	for (int i = 0; i < planes.Size(); i++) {
        delete planes[i];
    }
    if (d) {
        delete d;
    }
    planes.Clear();
}

/*
 * Adds the new projection plane.
 * point - the coordinates of an arbitrary point in plane
 * normal - normal vector of the plane
 */
void Projection::AddPlane(const Vector& point, const Vector& normal)
{
	planes.Add(new Plane(point, normal));
}

void Projection::AddPlane(const Plane& plane)
{
	planes.Add(new Plane(plane.GetPoint(), plane.GetNormal()));
}

/*
 * Sets the projection direction. The direction vector must 
 * point towards the projection planes.
 */
void Projection::SetDirection(const Vector& direction)
{
    if (d) {
        delete d;
    }
	d = new Vector(direction);
	d->Normalize();
}

// No description
Vector Projection::Project(const Vector& v) const
{
    assert(planes.Size() > 0);
    Vector n = planes[0]->GetNormal();
    if (n.DotProduct(*d) < 0) {
    	n = n * -1.0;
    }
    Vector p = planes[0]->GetPoint();
    double nxr = n.DotProduct(p);
    double nxr0 = n.DotProduct(v);
    double nxd = n.DotProduct(*d);
    Vector d1 = n * (nxr - nxr0);
    return v + ((*d) * (d1.Length() / nxd));
}
