// Class automatically generated by Dev-C++ New Class wizard

#ifndef SEGMENT_H
#define SEGMENT_H

#include "line.h" // inheriting class's header file

namespace engine3d {
  
    /**
     * Describes a line segment
     */
    class Segment : public Line
    {
    	public:
    		// class constructor
    		Segment(const Vector& rPoint1, const Vector& rPoint2);
    		// class destructor
    		~Segment();
            bool Contains(const Vector& rPoint) const;

    		bool IsSegment() const {
                return true;
            }
            
            bool Crosses(const Line& rLine) const;
            
    		
    };
}
#endif // SEGMENT_H
