// Class automatically generated by Dev-C++ New Class wizard

#ifndef SPATIAL_H
#define SPATIAL_H

#include "base/object.h"
#include "transformation.h"

using namespace base;

namespace engine3d {
    /**
     * Base class for all objects that can be transformed in space.
     * @see Camera
     * @see Node
     **/
    class Spatial : public Object
    {
    	protected:
    		/**
    		 * Constructs a spatial object
    		 **/
    		Spatial();
    		
    		/**
    		 * Constructs a spatial object with the given name
    		 **/
    		Spatial(const String& rName);
    		
    		/**
    		 * Copy constructor
    		 **/
    		Spatial(const Spatial& rSpatial);
    		
    		/**
    		 * Copies the given spatial object into this
    		 * object.
    		 **/
    		void Copy(const Spatial& rSpatial);
    		// class destructor
    		virtual ~Spatial();
    		
    	public:	
            /**
             * Sets the local transformation for this object.
             **/		
    		virtual void SetTransformation(const Transformation& rT);
    		/**
    		 * @return the local transformation for this object.
    		 **/
    		virtual const Transformation& GetTransformation() const;
    		/**
    		 * @return the world transformation for this object.
    		 * World transformation is calculated from local 
             * transformation and parent node's world transformation.
    		 **/
    		virtual const Transformation& GetWorldTransformation() const;

            virtual void Transform();
//    		virtual void SetNewTransformation(const Transformation& rT);
//    		virtual const Transformation& GetNewTransformation() const;
//    		virtual const Transformation& GetNewWorldTransformation() const;
    
            /**
             * @return true if this object has moved or rotated
             * in space after the scene was rendered last time
             **/		
    		virtual bool IsChanged() {return mChanged;}
    		
    		/**
    		 * Sets the object status to changed
    		 **/
    		//virtual void SetChanged(bool changed = true) {
            //    mChanged = changed;
            //}
    		
    	protected:
            
            /**
             * Current local transformation of the object
             **/
            Transformation mTransformation;
            
            /**
             * Current world transformation of the object. 
             * Recalculated in the  Init() method before each 
             * render if this is a node object. Equals to
             * mTransformation if this is a camera object.
             **/
            Transformation mWorldTransformation;
    
            /**
             * New local transformation of the object
             **/
            Transformation mNewTransformation;
            
            /**
             * New world transformation of the object. 
             **/
            Transformation mNewWorldTransformation;
        
            /**
             * Specified if this object has moved or rotated
             * after the scene was rendered last time
             **/
            bool mChanged;
            
    };
}
#endif // SPATIAL_H
