// Class automatically generated by Dev-C++ New Class wizard

#include <math.h>


#include "vector.h" // class's header file

using namespace engine3d;

//Vector::Vector()
//{
//}

// class constructor
Vector::Vector(int dim, bool zeroCoords)
{
    this->mDim = dim;
    this->mpCoords = new double[dim];
    if (zeroCoords) {
        for (int i = 0; i < dim; i++) {
            mpCoords[i] = 0;
        }
    }
}

// class constructor
Vector::Vector(int dim, double coords[])
{
    this->mDim = dim;
    this->mpCoords = new double[dim];
    for (int i = 0; i < dim; i++) {
    	this->mpCoords[i] = coords[i];
    }
}

Vector::Vector(double x, double y, double z, double w)
{
    mDim = 4;
    mpCoords = new double[mDim];
    mpCoords[0] = x;
    mpCoords[1] = y;
    mpCoords[2] = z;
    mpCoords[3] = w;
}

Vector::Vector(double x, double y, double z)
{
    mDim = 3;
    mpCoords = new double[mDim];
    mpCoords[0] = x;
    mpCoords[1] = y;
    mpCoords[2] = z;
}

Vector::Vector(double x, double y)
{
    mDim = 2;
    mpCoords = new double[mDim];
    mpCoords[0] = x;
    mpCoords[1] = y;
}

Vector::Vector(double x)
{
    mDim = 1;
    mpCoords = new double[mDim];
    mpCoords[0] = x;
}

Vector::Vector(const Vector& v)
{
    mDim = v.mDim;
    mpCoords = new double[mDim];
    for (int i = 0; i < mDim; i++) {
    	mpCoords[i] = v.mpCoords[i];
    }
}

Vector& Vector::operator=(const Vector& v) {
    if (this != &v) {
        if (mpCoords) {
            delete mpCoords;
        }
        mDim = v.mDim;
        mpCoords = new double[mDim];
        for (int i = 0; i < mDim; i++) {
            mpCoords[i] = v.mpCoords[i];
        }
    }
    return *this;
}

Vector Vector::operator-() const {
    Vector v(mDim, false);//(*this);
    for (int i = 0; i < mDim; i++) {
        v.mpCoords[i] = -mpCoords[i];
    }
    return v;
}


double Vector::operator[](int i) const {
    assert(i >= 0 && i < mDim);
    return mpCoords[i];
}

Vector Vector::operator+(const Vector& v) const {
    assert(mDim == v.mDim);
    Vector result(mDim, false);
    for (int i = 0; i < mDim; i++) {
        result.mpCoords[i] = mpCoords[i] + v.mpCoords[i];
    }
    return result;
}

Vector Vector::operator-(const Vector& v) const {
    assert(mDim == v.mDim);
    Vector result(mDim, false);
    for (int i = 0; i < mDim; i++) {
        result.mpCoords[i] = mpCoords[i] - v.mpCoords[i];
    }
    return result;
}

Vector Vector::operator*(double c) const {
    Vector result(mDim, false);
    for (int i = 0; i < mDim; i++) {
        result.mpCoords[i] = mpCoords[i] * c;
    }
    return result;
}

Vector Vector::operator/(double c) const {
    Vector result(mDim, false);
    for (int i = 0; i < mDim; i++) {
        result.mpCoords[i] = mpCoords[i] / c;
    }
    return result;
}

Vector& Vector::operator+=(const Vector& v) {
    assert(mDim == v.mDim);
    for (int i = 0; i < mDim; i++) {
        mpCoords[i] += v.mpCoords[i];
    }
    return *this;
}

Vector& Vector::operator-=(const Vector& v) {
    assert(mDim == v.mDim);
    for (int i = 0; i < mDim; i++) {
        mpCoords[i] -= v.mpCoords[i];
    }
    return *this;
}

Vector& Vector::operator*=(double c) {
    for (int i = 0; i < mDim; i++) {
        mpCoords[i] *= c;
    }
    return *this;
}

Vector& Vector::operator/=(double c) {
    for (int i = 0; i < mDim; i++) {
        mpCoords[i] /= c;
    }
    return *this;
}

// class destructor
Vector::~Vector()
{
    if (mpCoords) {
	   delete []mpCoords;
    }
}

// returns the coordinate of this vector at the specified index
//double Vector::GetCoord(int index) const 
//{
//    assert(dim > index);
//	return coords[index];
//}

void Vector::SetCoord(int index, double d) 
{
	mpCoords[index] = d;
}

//double Vector::GetX() const 
//{
//    assert(dim > 0);
//	return coords[0];
//}
//
//double Vector::GetY() const 
//{
//    assert(dim > 1);
//	return coords[1];
//}
//
//double Vector::GetZ() const 
//{
//    assert(dim > 2);
//	return coords[2];
//}
//
//double Vector::GetW() const 
//{
//    assert(dim > 3);
//	return coords[3];
//}

//void Vector::Add(const Vector& v)
//{
//    assert(v.GetDim() == dim);
//    for (int i = 0; i < dim; i++) {
//        coords[i] += v.GetCoord(i);
//    }
//}
//
//void Vector::Mul(const double c)
//{
//    for (int i = 0; i < dim; i++) {
//        coords[i] *= c;
//    }
//}
//
//void Vector::Sub(const Vector& v)
//{
//    assert(v.GetDim() == dim);
//    for (int i = 0; i < dim; i++) {
//        coords[i] -= v.GetCoord(i);
//    }
//}

// Calculates the scalar product of the given vector and this vector
double Vector::DotProduct(const Vector& v) const
{
    assert(v.mDim == mDim);
    double product = 0;
    for (int i = 0; i < mDim; i++) {
        product += v.mpCoords[i] * mpCoords[i];
    }
	return product;
}

Vector Vector::CrossProduct(const Vector& v) const
{
    assert(v.mDim == mDim && mDim == 3);
    double vx = mpCoords[1] * v.mpCoords[2] - mpCoords[2] * v.mpCoords[1];
    double vy = mpCoords[2] * v.mpCoords[0] - mpCoords[0] * v.mpCoords[2];
    double vz = mpCoords[0] * v.mpCoords[1] - mpCoords[1] * v.mpCoords[0];
	return Vector(vx, vy, vz);
}

// Returns the dimention of this vector
int Vector::GetDim() const
{
	return mDim;
}

// Returns the norm of this vector
double Vector::Length() const
{
    if (mDim == 1) {
        return fabs(mpCoords[0]);
    }
	return sqrt(DotProduct(*this));
}

// Returns the squared norm of this vector
double Vector::Length2() const
{
	return DotProduct(*this);
}

// Normalizes the vector and returns the reference to this
Vector& Vector::Normalize() {
    *this /= Length();
    return (*this);
}

Vector Vector::GetProjection(const Vector& axis) const {
    Vector projection = Vector(axis).Normalize();
    return projection * projection.DotProduct(*this);
}

String Vector::ToString() const {
    String s;
    for (int i = 0; i < mDim; i++) {
        if (i != 0) {
            s = s + ",";
        }
        s = s + mpCoords[i];
    }
    return s;
}
