// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOUNDINGSPHERE_H
#define BOUNDINGSPHERE_H

#include "boundingvolume.h" // inheriting class's header file
#include "engine3d/geometry/vector.h"

using namespace base;

namespace engine3d {
/*
 * No description
 */
class BoundingSphere : public BoundingVolume
{
	public:
		// class constructor
		BoundingSphere(const Vector& rPos, double radius);

		BoundingSphere* Clone() const;

		// class destructor
		~BoundingSphere();
		
		int WhichSide(const Plane& rPlane) const;

        bool Intersects(const Line& rLine) const;
        
   		bool Collides(const BoundingVolume& rOtherBound) const;

        void Transform();
	private:
        Vector mPosition;
        double mRadius;
        Vector mTransformedPosition;
};
}
#endif // BOUNDINGSPHERE_H
