// Class automatically generated by Dev-C++ New Class wizard

#include "boundingvolume.h" // class's header file

using namespace engine3d;

// class constructor
BoundingVolume::BoundingVolume()
{
	// insert your code here
}

// class destructor
BoundingVolume::~BoundingVolume()
{
	// insert your code here
}
