// Class automatically generated by Dev-C++ New Class wizard

#include "color.h" // class's header file

using namespace engine3d;
// class constructor
//Color::Color(double r, double g, double b, double a) :
//	red(red),
//	green(g),
//	blue(b),
//	alpha(a)
//
//{
//}

Color::Color(const double& r, const double& g, const double& b, const double& a) :
    red(r),
    green(g),
    blue(b),
    alpha(a)
{
}

// class destructor
Color::~Color()
{
	// insert your code here
}
