// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEXTURE_H
#define TEXTURE_H

#include <gl.h>
#include "base/object.h"
#include "lodepng/lodepng.h"

using namespace base;

namespace engine3d {

/*
 * No description
 */
class Texture : public Object
{
	public:
		/**
		 * Creates a new texture
		 * @param textureFile png file of the texture image.
         * The height and width of the texture image must be multiples of 2.
		 * @param name name of the texture
		 * @param format texture format (one of the above constants)
		 **/
		Texture(const String& textureFile, const String& name = "");
		// class destructor
		~Texture();
		
		/**
		 * Modulates this texture with another texture.
		 * RGBA texture can be constructed from
		 * RGB texture by modulating it with ALPHA texture
		 **/
		Texture& Modulate(const Texture& texture);

		/**
		 * @return pointer to the texture image data that can be used as an
		 * input parameter for glTextImage2D function
		 **/
		const void* GetPixels() {
            return &((*mpImage)[0]);
        }
        
		// No description
		unsigned GetHeight() {
            return mHeight;
        }
        
		// No description
		unsigned GetWidth() {
            return mWidth;
        }
        
	protected:
        std::vector<unsigned char>* mpImage;
        unsigned mWidth, mHeight;
};
}
#endif // TEXTURE_H
