// Class automatically generated by Dev-C++ New Class wizard

#ifndef DISC_H
#define DISC_H

#include "trianglefan.h"
#include <math.h>

using namespace base;

namespace engine3d {
/*
 * No description
 */
class Disc : public TriangleFan
{
	public:
		// class constructor
		Disc(double radius, int slices);
		// class destructor
		~Disc();
		virtual void Render();
};
}
#endif // DISC_H
