// Class automatically generated by Dev-C++ New Class wizard

#include "disc.h" // class's header file

using namespace engine3d;
// class constructor
Disc::Disc(double r, int slices)
{
    double phi = 0;
    double dPhi = 2.0 * M_PI / slices;
    double x;
    double y;
    for (int i = 0; i < slices; i++) {
        x = r * cos(phi);
        y = r * sin(phi);
        AddVertex(Vertex(x ,y , 0));
        phi += dPhi;
    }
}

// class destructor
Disc::~Disc()
{
    // TODO: delete vertices
	// insert your code here
}

void Disc::Render() 
{
    TriangleFan::Render();
}
