// Class automatically generated by Dev-C++ New Class wizard

#ifndef MESH_H
#define MESH_H

#include "shape.h"
#include "engine3d/geometry/vector.h"
#include "vertex.h"
#include "base/list.h"

using namespace base;

namespace engine3d {
/*
 * Defines a set of vertices
 * This class should be renamed to Mesh
 */
class Mesh : public Shape
{
	public:
		// class constructor
		Mesh(int type);
		// copy contructor
		//Vertices(const Vertices& vs);
	protected:
		void Copy(const Mesh& rMesh);
	public:
		virtual Mesh* Clone();
		// class destructor
		virtual ~Mesh();
		// Adds a vertex to the mesh
		void AddVertex(const Vertex& vertex);
		void AddVertex(const Vector& v, const Color& color);
		void AddVertex(const Vector& v, const Vector& texCoords);
		// Returns the vertex at the given index
		//Vertex& GetVertex(int index) const;
		int GetSize() const;
		virtual void Render();
		// Generates texture coordinates for the vertices
		virtual void GenTexCoords();
		// No description
		void SetTexCoords(List<Vector*>& texCoords);
		/**
		 * Projects the front face of the vertices to the far plane 
		 * of the clipping area
		 **/
		virtual Shape* GetDistantProjection();
        /**
         * Overrides Node::Sort - no sorting of vertices is desired
         **/
        void Sort() {}
	protected:
	protected:
        //vector<Vertex*> vertices;
        int type;
};
}
#endif // MESH_H
