// Class automatically generated by Dev-C++ New Class wizard

#include <GL/gl.h>

#include "shape.h" // class's header file

using namespace engine3d;
// class constructor
Shape::Shape(const String& name) : Node(name),
	    mpTexture(nullptr),
	    mpColor(nullptr)
{

}

Shape::Shape(const Shape& rShape) : Node(rShape) {
	mpTexture = rShape.mpTexture;
	mpColor = rShape.mpColor;
}

void Shape::Copy(const Shape& rShape)
{
    Node::Copy(rShape);
    mpTexture = rShape.mpTexture;
    mpColor = rShape.mpColor;
}

Shape* Shape::Clone() const
{
    Debug("Shape.Clone");
    Shape* p_shape = new Shape();
    p_shape->Copy(*this);
    return p_shape;
}

// class destructor
Shape::~Shape()
{
}

void Shape::BeginRender() 
{
    //static Texture* ps_texture = 0;
    if (mpTexture) {// && mpTexture != ps_texture) {
    	mpTexture->Use();
    }
    else if (mpColor) {
		glColor4d(mpColor->red, mpColor->green, mpColor->blue, mpColor->alpha);
    }
}

void Shape::EndRender() 
{
}

void Shape::Render()
{
    //long millis = GetMillis();
    //Debug("Shape::Render");
    BeginRender();
    Node::Render();
    EndRender();
    //Debug(String("Shape::Render took ") + (GetMillis() - millis));
}

// No description
void Shape::SetTexture(Texture* pTexture)
{
    mpTexture = pTexture;
}

Texture* Shape::GetTexture()
{
    return mpTexture;
}

void Shape::SetColor(const Color& rColor)
{
    if (mpColor) {
        delete mpColor;
    }
    mpColor = new Color(rColor.red, rColor.green, rColor.blue, rColor.alpha);
}

void Shape::RemoveColor()
{
    if (mpColor) {
        delete mpColor;
    }
    mpColor = 0;
}
