// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRIANGLEFAN_H
#define TRIANGLEFAN_H

#include "mesh.h" // inheriting class's header file

using namespace base;

namespace engine3d {

/*
 * No description
 */
class TriangleFan : public Mesh
{
	public:
		// class constructor
		TriangleFan();
	protected:
        void Copy(const TriangleFan& ts);
    public:
        virtual TriangleFan* Clone() const;
		// class destructor
		~TriangleFan();
		virtual void Render();
		virtual Shape* GetDistantProjection();
};
}
#endif // TRIANGLEFAN_H
