// Class automatically generated by Dev-C++ New Class wizard

#include <GL/gl.h>

#include "vertex.h"

using namespace engine3d;

Vertex::Vertex() : mCoords(0, 0, 0)
{
    mpColor = nullptr;
    mpTexCoords = nullptr;
}

Vertex::Vertex(double x, double y, double z) : mCoords(x, y, z)
{
    mpColor = nullptr;
    mpTexCoords = nullptr;
}

Vertex::Vertex(const Vector& v) : mCoords(v) {
    mpColor = nullptr;
    mpTexCoords = nullptr;
}

Vertex::Vertex(const Vertex& v) : mCoords(v.mCoords) {
    mpColor = nullptr;
    mpTexCoords = nullptr;
    if (v.mpTexCoords) {
        mpTexCoords = new Vector(*v.mpTexCoords);
    }
    if (v.mpColor) {
        mpColor = new Color(v.mpColor->red, v.mpColor->green, v.mpColor->blue, v.mpColor->alpha);
    }
}

Vertex::Vertex(const Vertex& vertex, const Vector& vect) : mCoords(vect) {
    mpColor = nullptr;
    mpTexCoords = nullptr;
    if (vertex.mpTexCoords) {
        mpTexCoords = new Vector(*vertex.mpTexCoords);
    }
    if (vertex.mpColor) {
        mpColor = new Color(vertex.mpColor->red, vertex.mpColor->green, vertex.mpColor->blue, vertex.mpColor->alpha);
    }
}

Vertex* Vertex::Clone() const
{
    Debug("Vertex.Clone");
    return new Vertex(*this);
}

// class destructor
Vertex::~Vertex()
{
    if (mpTexCoords) {
        delete mpTexCoords;
    }
    if (mpColor) {
        delete mpColor;
    }
}

void Vertex::SetColor(const Color& c)
{
    if (mpColor) {
        delete mpColor;
    }
    mpColor = new Color(c.red, c.green, c.blue, c.alpha);
}

void Vertex::SetCoords(const Vector& coords)
{
    assert(coords.GetDim() == 3);
    this->mCoords = coords;
}

void Vertex::SetCoords(double x, double y, double z)
{
    this->mCoords = Vector(x, y, z);
}

void Vertex::SetTexCoords(const Vector& texCoords)
{
    assert(texCoords.GetDim() == 2);
    SetTexCoords(texCoords[0], texCoords[1]);
}

void Vertex::SetTexCoords(double s, double t)
{
    //Debug("set tex coords");
    if (mpTexCoords) {
        //Debug("set tex coords0");
        delete mpTexCoords;
    }
    //Debug("set tex coords1");
    if (s < 0.0f) {
        s = 0.0f;
    }
    if (t < 0.0f) {
        t = 0.0f;
    }
    if (s > 1.0f) {
        s = 1.0f;
    }
    if (t > 1.0f) {
        t = 1.0f;
    }
    //Debug("set tex coords2");
    this->mpTexCoords = new Vector(s, t);
    //Debug("set tex coords3");
}

void Vertex::Init()
{
    //long millis = GetMillis();
    Node::Init();
    //Debug(String("Vertex::Init took ") + (GetMillis() - millis));
}

void Vertex::Render()
{
    //long millis = GetMillis();
    Node::Render();
    if (mpColor) {
        glColor4d(mpColor->red, mpColor->green, mpColor->blue, mpColor->alpha);
    }
    if (mpTexCoords) {
        //Debug(String("V::R tc ") + (*texCoords)[0] + ", " + (*texCoords)[1]);
        glTexCoord2d((*mpTexCoords)[0], (*mpTexCoords)[1]);
    }
	////Debug(String("WC V::R ") + (worldCoords)[0] + ", " + (worldCoords)[1] + ", " + (worldCoords)[2]);
	//Debug((String) "V::R " + (coords)[0] + ", " + (coords)[1] + ", " + (coords)[2]);
	glVertex3d((mCoords)[0], (mCoords)[1], (mCoords)[2]);
    //Debug(String("Vertex::Render took ") + (GetMillis() - millis));
}

