// Class automatically generated by Dev-C++ New Class wizard

#include "controller.h" // class's header file

using namespace engine3d;

// class constructor
Controller::Controller(const Scene& rScene) :
    mrScene(rScene)
{
}

// class destructor
Controller::~Controller()
{
	// insert your code here
}
