// Class automatically generated by Dev-C++ New Class wizard

#ifndef KEYCONTROLLER_H
#define KEYCONTROLLER_H

#include "transformationcontroller.h" // inheriting class's header file

using namespace base;

namespace engine3d {
/*
 * No description
 */
class KeyController : public TransformationController
{
	public:
		// class constructor
		KeyController(const Scene& rScene);
		// class destructor
		~KeyController();
};
}
#endif // KEYCONTROLLER_H
