// Class automatically generated by Dev-C++ New Class wizard

#include "keycontroller.h" // class's header file

using namespace engine3d;

// class constructor
KeyController::KeyController(const Scene& rScene) :
    TransformationController(rScene)
{
	// insert your code here
}

// class destructor
KeyController::~KeyController()
{
	// insert your code here
}
