// Class automatically generated by Dev-C++ New Class wizard

#ifndef MOUSECONTROLLER_H
#define MOUSECONTROLLER_H

#include "transformationcontroller.h" // inheriting class's header file

using namespace base;

namespace engine3d {
/*
 * No description
 */
class MouseController : public TransformationController
{
	public:
		// class constructor
		MouseController(const Scene& rScene);
		// class destructor
		~MouseController();
		void OnMove(int xPos, int yPos);
		void OnButton(int button, int state, int x, int y);
	protected:
		int* mpButton;
		int* mpModifier;
        int x;
        int y;
};
}
#endif // MOUSECONTROLLER_H
