// Class automatically generated by Dev-C++ New Class wizard

#ifndef BODY_H
#define BODY_H

#include "engine3d/scenegraph/node.h" // inheriting class's header file
#include "engine3d/geometry/vector.h"

namespace engine3d {
    /**
     * Class containing physical properties of body
     */
    class Body : public Node
    {
    	public:
    		// class constructor
    		Body(double mass = 0);
    		// class destructor
    		~Body();
    		
    		/**
    		 * Applies an external force to body
    		 **/
    		void SetForce(const Vector& rForce);

            const Vector& GetForce() const {
                return mForce;
            }
    		
    		void SetVelocity(const Vector& rVelocity) {
                mVelocity = rVelocity;
            }

            const Vector& GetVelocity() const {
                return mVelocity;
            }

    		/**
    		 * Moves the body according to external
    		 * forces during the given time span.
    		 **/
    		void Move(double dt);
    		
    		// @Override Node::Init
    		void Init();
    		
    		// @Override Node::IsChanged
    		bool IsChanged();
            
    	protected:
            /**
             * Mass of the body
             **/
            double mMass;
            
            /**
             * Velocity of the body
             **/
            Vector mVelocity;
            
            /**
             * External forces applied to body
             **/
            Vector mForce;
    };
}
#endif // BODY_H
