// Class automatically generated by Dev-C++ New Class wizard

#include "particle.h" // class's header file

using namespace engine3d;

// class constructor
Particle::Particle()
{
	// insert your code here
}

// class destructor
Particle::~Particle()
{
	// insert your code here
}
