// Class automatically generated by Dev-C++ New Class wizard

#ifndef PARTICLE_H
#define PARTICLE_H

#include "engine3d/meshes/vertex.h" // inheriting class's header file

namespace engine3d {
    /**
     * Class cointaining physical properties of a point
     * mass body.
     */
    class Particle : public Vertex
    {
    	public:
    		// class constructor
    		Particle();
    		// class destructor
    		~Particle();
    	protected:
            double mMass;
            Vector mVelocity;
            
    };
}
#endif // PARTICLE_H
